basket_app/urls.py
from django.urls import path
from basket_app import views

app_name = 'basket_app'

urlpatterns = [
    path('basket_add/', views.basket_add, name='basket_add'),
    path('basket_change/', views.basket_change, name='basket_change'),
    path('basket_remove/', views.basket_remove, name='basket_remove'),
]

products_app/urls.py
from django.urls import path
from products_app import views

app_name = 'products_app'

urlpatterns = [
    path('search/', views.catalog, name='search'),
    path('<int:category_id>/', views.catalog, name='index'),
    path('products/<int:product_id>/', views.products, name='products'),
    path('products/<slug:product_slug>/', views.products, name='products'),

]

store/urls.py
from django.contrib import admin
from django.urls import path, include
#from main_app import views
from store import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls', namespace='main_app')),
    path('catalog/', include('products_app.urls', namespace='catalog')),
    path('user/', include('users_app.urls', namespace='user')),
    path('basket/', include('basket_app.urls', namespace='basket')),
    path('orders/', include('orders.urls', namespace='orders')),
    path("__debug__/", include("debug_toolbar.urls")), #DEBUG режим
    #static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
]

if settings.DEBUG:

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products_app/models.py
from django.db import models

from django.urls import reverse


class Categories(models.Model):
    name = models.CharField(max_length=100, unique=True, verbose_name='Группа')

    def __str__(self):
        return f"{self.name},{self.id}"

    class Meta:

        verbose_name = 'Группа'
        verbose_name_plural = 'Группы'

    def __str__(self):
        return self.name

class Recipe_status(models.Model):
    name = models.CharField(max_length=100, unique=True, verbose_name='Рецептурный статус')

    class Meta:
        verbose_name = 'Рецептурный статус'
        verbose_name_plural = 'Рецептурные статусы'

    def __str__(self):
        return self.name

class Storage_conditions(models.Model):
    name = models.CharField(max_length=50, unique=True, verbose_name='Условия хранения')

    class Meta:
        verbose_name = 'Условия хранения'
        verbose_name_plural = 'Условия хранения'

    def __str__(self):
        return self.name

class Price_category(models.Model):
    name = models.CharField(max_length=50, unique=True, verbose_name='Ценовая категория')

    class Meta:
        verbose_name = 'Ценовая категория'
        verbose_name_plural = 'Ценовые категории'

    def __str__(self):
        return self.name


class Products(models.Model):
    name = models.CharField(max_length=150, unique=True, verbose_name='Название и дозировка')
    slug = models.SlugField(max_length=200, unique=True, blank=True, null=True, verbose_name='URL')
    description = models.TextField(blank=True, null=True, verbose_name='Инструкция')
    image = models.ImageField(upload_to='products_images', blank=True, null=True, verbose_name='Изображение')
    price = models.DecimalField(default=0.00, max_digits=7, decimal_places=2, verbose_name='Цена базовая')
    discount = models.DecimalField(default=0.00, max_digits=4, decimal_places=2, verbose_name='Скидка в %')
    quantity = models.PositiveIntegerField(default=0, verbose_name='Количество')
    category = models.ForeignKey(to=Categories, on_delete=models.PROTECT, verbose_name='Группа')
    price_category = models.ForeignKey(to=Price_category, on_delete=models.PROTECT, verbose_name='Ценовая категория')
    storage_conditions = models.ForeignKey(to=Storage_conditions, on_delete=models.PROTECT, verbose_name='Условия хранения')
    recipe_status= models.ForeignKey(to=Recipe_status, on_delete=models.PROTECT, verbose_name='Рецептурный статус')


    class Meta:
        db_table = 'product'
        verbose_name = 'Продукт'
        verbose_name_plural = 'Продукты'
        ordering = ('name',)

    def __str__(self):
        return f"{self.name}, Количество {self.quantity}"

    def display_id(self):
        return f"{self.id:06}"

    def retail_price(self):
        if self.discount:
            return round(self.price - self.price * self.discount / 100, 2)

        return self.price

products_app/views.py
from django.shortcuts import render, get_list_or_404
from django.http import Http404
from django.views.generic import DetailView, ListView
from django.core.paginator import Paginator
from products_app.models import Products
from products_app.utils import q_search


def catalog(request, category_id=None):
    page = request.GET.get('page', 1)
    on_sale = request.GET.get('on_sale', None)
    order_by = request.GET.get('order_by', None)
    query = request.GET.get('q', None)

    if category_id == 1:
        products_app = Products.objects.all()
    elif query:
        products_app = q_search(query)
    else:
        products_app = get_list_or_404(Products.objects.filter(category__id=category_id)) #ORM -запрос

    if on_sale:
        products_app = products_app.filter(discount__gt=0)
    if order_by and order_by !='default':
        products_app = products_app.order_by(order_by)

    paginator = Paginator(products_app, 3)
    current_page = paginator.page(int(page))

    context = {
        "title": "Home - Каталог",
        "products_app": current_page,
        "id_url":category_id,

    }
    return render(request, "products_app/catalog.html", context)


def products(request, product_slug=False, product_id=False):
    if product_id:
        product = Products.objects.get(id=product_id) #ORM

    else:
        product = Products.objects.get(slug=product_slug)
    context = {"product": product}

    return render(request, "products_app/products.html", context=context)

# {% user_basket request as baskets %}
# {% with baskets=user_basket request %}

products_app/templates/products_app/catalog.html
{% extends "base.html" %}
{% load static %}
{% load product_tags %}


{% block content %}
<div class="row">

    <!-- Форма фильтров -->
    <div class="dropdown mb-2">
        <button class="btn btn-secondary dropdown-toggle btn-dark" type="button" data-bs-toggle="dropdown" aria-expanded="false"> Фильтры
        </button>

            <form action='{% if request.GET.q %}{% url "catalog:search" %}{% else %}{% url "catalog:index" id_url %}{% endif %}' method="get" class="dropdown-menu bg-dark" data-bs-theme="dark">
                <div class="form-check text-white mx-3">
                <input class="form-check-input" type="checkbox" name="on_sale" id="flexCheckDefault" value="on" {% if request.GET.on_sale == 'on' %} checked {% endif %}>

                <label class="form-check-label" for="flexCheckDefault">
                {% if request.GET.q %}
                    <input type="hidden" name="q" value="{{ request.GET.q }}">
                {% endif %}>
                <label class="form-check-label" for="flexCheckDefault">
                    Товары со скидкой
                </label>
            </div>
            <p class="text-white mx-3 mt-3">Сортировать:</p>
            <div class="form-check text-white mx-3">
                <input class="form-check-input" type="radio" name="order_by" id="flexRadioDefault1" value="default"
                    {% if not request.GET.order_by or request.GET.oder_by == 'default' %} checked {% endif %}>
                <label class="form-check-label" for="flexRadioDefault1">
                    По умолчанию
                </label>
            </div>
            <div class="form-check text-white mx-3">
                <input class="form-check-input" type="radio" name="order_by" id="flexRadioDefault2" value="price"
                       {% if request.GET.order_by == 'price' %} checked {% endif %}>
                <label class="form-check-label" for="flexRadioDefault2">
                    От дешевых к дорогим
                </label>
            </div>
            <div class="form-check text-white mx-3">
                <input class="form-check-input" type="radio" name="order_by" id="flexRadioDefault3" value="-price"
                       {% if request.GET.order_by == '-price' %} checked {% endif %}>
                <label class="form-check-label" for="flexRadioDefault3">
                    От дорогих к дешевым
                </label>
            </div>
            <button type="submit" class="btn btn-primary mx-3 mt-3">Применить</button>
        </form>
    </div>

    {% if request.GET.q %}
    <h3 class="mt-4">Результаты поиска по запросу {{ request.GET.q }}</h3>
    {% if not products_app %}
        <link rel="stylesheet" href="{% static 'deps/css/my_footer_css.css' %}">
        <h2 class="mt-4">По запросу ничего не найдено</h2>
    {% endif %}
    {% endif %}
    {% for product in products_app %}
        <!-- Карта товара -->

        <div class='card' style="width: 18rem;">

            <div class="card border-primary rounded ">
                {% if product.image %}
                    <img src="{{ product.image.url }}" class="card-img-top" alt="{{ product.name }}">
                {% else %}
                    <img src="{% static 'deps/images/Not found image.png' %}" class="card-img-top" alt="...">
                {% endif %}
                <div class="card-body">
                    <a href="{% url 'catalog:products' product.slug %}">
                        <p class="card-title">{{ product.name }}</p>
                    </a>
                    <p class="card-text ">{{ product.description|truncatechars:40 }}</p>
                    <p class="product_id">id: {{ product.display_id }}</p>
                    <div class="d-flex justify-content-between">
                        {% if product.discount %}
                            <p><s>{{ product.price }}</s> руб.</p>
                            <p><strong>{{ product.retail_price }} руб.</strong></p>
                            <span class="badge bg-warning text-dark">Скидка {{ product.discount }} %</span>
                        {% else %}
                            <p><strong>{{ product.price }} руб.</strong></p>
                        {% endif %}


                        <a href="{% url 'basket:basket_add' %}" class="btn add-to-basket"
                        data-product-id="{{ product.id }}">
                            {% csrf_token %}
                            <img class="mx-1" src="{% static 'deps/icons/basket.png' %}" alt="Catalog Icon"
                                width="32" height="32">
                        </a>
                    </div>
                </div>
            </div>
        </div>
    {% endfor %}


</div>
<!-- Пагинация -->
{% if products_app %}

<nav aria-label="Page navigation example">
    <ul class="pagination justify-content-center my-4">
        <div class="custom-shadow d-flex">
            <li class="page-item {% if not products_app.has_previous %}disabled{% endif %}">
              <a class="page-link" href="{% if products_app.has_previous %}?{% change_params page=products_app.previous_page_number %}{% else %}
                #
              {% endif %}">Назад</a>
            </li>
            {% for page in products_app.paginator.page_range %}
            {% if page >= products_app.number|add:-2 and page <= products_app.number|add:2 %}
                <li class="page-item"><a class="page-link" href="?{% change_params page=page %}">{{ page }}</a></li>
            {% endif %}
            {% endfor %}
            <li class="page-item {% if not products_app.has_next %}disabled{% endif %}">
              <a class="page-link" href="{% if products_app.has_next %}?{% change_params page=products_app.next_page_number %}{% else %}
                #
              {% endif %}">Вперед</a>
            </li>

        </div>
    </ul>
</nav>
{% endif %}
{% endblock  %}


{% block footer %}
<footer class="py-2 bg-dark">
    <link rel="stylesheet" href="{% static 'deps/css/my_footer_css.css' %}">
    <div class="container">
        <p class="m-0 text-center text-white"> Мой диплом 2024</p>
    </div>
</footer>
{% endblock  %}

products_app/templates/products_app/products.html
{% extends "base.html" %}
{% load static %}


{% block content %}
<div class="container mt-4">
    <div class="card mb-4 custom-shadow">
        <div class="row">
            <!-- Миниатюры -->
            <div class="col-md-4">
                {% if product.image %}
                <img src="{{ product.image.url }}"
                    class="img-thumbnail" data-bs-toggle="modal" data-bs-target="#imageModal1">
                {% endif %}
                <!-- Описание товара -->
                    <div class="card-body" >
                        <p class="card-text">Цена: <strong> {{ product.retail_price }} руб.</strong></p>
                        <h5 class="card-title">{{ product.name }}</h5>
                        <p class="card-text">{{ product.description }}</p>
                        <a href="{% url 'basket:basket_add' %}" class="btn btn-dark add-to-basket"
                        data-product-id="{{ product.id }}">
                        {% csrf_token %}
                        Добавить в корзину</a>
                    </div>
            </div>
            <div class="col-md-4 ">
                <p class="product_id mt-5">id: {{ product.display_id }}</p>
            </div>
            <!-- Увеличить изображение в модальном окне -->
            <div class="modal fade" id="imageModal1" tabindex="-1"
                aria-labelledby="imageModal1Label" aria-hidden="true">
                <div class="modal-dialog modal-lg">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title" id="imageModal1Label">{{ product.name }}</h5>
                            <button type="button" class="btn-close" data-bs-dismiss="modal"
                                aria-label="Закрыть"></button>
                        </div>
                        {% if product.image %}

                            <img src="{{ product.image.url }}"
                        {% endif %}
                                 <div class="modal-body">

                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>
</div>
{% endblock  %}